export const USER_INPUT_PASSWORD_CHANGED = 'USER_INPUT_PASSWORD_CHANGED';
export const USER_INPUT_LOGIN_CHANGED = 'USER_INPUT_LOGIN_CHANGED';
export const USER_INPUT_NAME_CHANGED = 'USER_INPUT_NAME_CHANGED';
export const USER_INPUT_SURNAME_CHANGED = 'USER_INPUT_SURNAME_CHANGED';
export const USER_INPUT_INVITED_CHANGED = 'USER_INPUT_INVITED_CHANGED';
export const USER_INPUT_COUNTRY_KEY_CHANGED = 'USER_INPUT_COUNTRY_KEY_CHANGED';
export const USER_INPUT_PHONE_CHANGED = 'USER_INPUT_PHONE_CHANGED';

export const USER_TRY_TO_LOG_IN = 'USER_TRY_TO_LOG_IN';
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
export const USER_LOG_IN_FAILED = 'USER_LOG_IN_FAILED';

export const USER_ALREADY_LOGIN = 'USER_ALREADY_LOGIN';
export const USER_TRY_TO_RELOG_IN = 'USER_TRY_TO_RELOG_IN';

export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const USER_TRY_TO_CREATE = 'USER_TRY_TO_CREATE';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL';

export const USER_CLEAR_STATE= 'USER_CLEAR_STATE';

